### ISSUE TITLE
CSS logical properties break in certain cases

### ISSUE THREAD

**Issue by rococosans** [sveltejs/sapper#1041]
CSS logical properties are fairly new browser feature that aren't yet supported in all browsers. That said, I wanted to post this for awareness.

https://caniuse.com/#feat=css-logical-props

Bug:
Using CSS logical properties is a style tag breaks the build under certain circumstances.

I've found that:
1. If there is a :global() in use in the same style tag as a logical property, that triggers an error
2. Using CSS logical properties in a media query also breaks things

Logs:

```
✗ client
Cannot read property 'file' of undefined
✔ server (1.5s)
```

ENV:
Windows 10
Chrome/79.0.3945.88
sapper: "0.27.9",
svelte: "3.16.5",
svelte-preprocess: "3.3.0"
node-sass: "4.13.0",
postcss-preset-env: "6.7.0",
rollup: "1.27.13",

The problem doesn't appear to be caused my CSS preprocessing, but it very well could be. Nonetheless, I wanted to share what was happening. Thank you!

**Comment by rococosans** [comment]
Does not work:

```css
:global(.theater_mode) .playlist_container_outer {
  margin-block-start: 0;
  margin-inline-start: 0;
}
```

Error:

```css
✗ client
C:\path\file.svelte
:global(...) can be at the start or end of a selector sequence, but not in the middle
176:   width: 100%; }
177:
178: [dir="ltr"] :global(.theater_mode) .playlist_container_outer {
                 ^
179:   margin-left: 0; }
180:
✗ server
C:\path\file.svelte
:global(...) can be at the start or end of a selector sequence, but not in the middle
176:   width: 100%; }
177:
178: [dir="ltr"] :global(.theater_mode) .playlist_container_outer {
                 ^
179:   margin-left: 0; }
180:
```

However, this is working:

```css
:global(.theater_mode) .playlist_container_outer {
  margin-block-start: 0;
  margin-left: 0;
}
```
